version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    env_file: 
      - .env
    volumes:
      - .:/usr/src/app
  mongodb:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    env_file: 
      - .env
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data:/data/db
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/usr/src/app
    env_file: 
      - .env.test
    depends_on:
      - mongodb_test
  mongodb_test:
    image: mongo:6-jammy
    ports:
      - "27018:27017"
    env_file: 
      - .env.test
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_test_data:/data/db

volumes:
  mongodb_data:
  mongodb_test_data: